# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main, prod ]
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    branches: [ main, prod ]

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.pull_request.draft == false
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Check JSONs
      run: |
        python -c "import json; from pathlib import Path; [json.load(open(str(i))) for i in Path('.').glob('**/*.json*') if '/env/' not in str(i)];"